# Generated by cucumber-sinatra. (2011-08-19 13:21:20 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'game.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Bowlind

class BowlindWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BowlindWorld.new
end
